# Generated by Django 3.2.9 on 2021-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doseerpomp',
            name='handlername',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
