# Generated by Django 3.2.9 on 2021-11-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doseerpomp_handlername'),
    ]

    operations = [
        migrations.AddField(
            model_name='doseerstraat',
            name='handlername',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literteller',
            name='handlername',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetstraat',
            name='handlername',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systeempomp',
            name='handlername',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterfilter',
            name='handlername',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
