# Generated by Django 3.2.9 on 2021-11-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211123_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phsensorvoor',
            old_name='value',
            new_name='s1',
        ),
        migrations.AddField(
            model_name='phsensorna',
            name='s1',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phsensorna',
            name='s2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phsensorna',
            name='s3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phsensorvoor',
            name='s2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phsensorvoor',
            name='s3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
